# Generated by Django 3.2.2 on 2021-05-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Долгота')),
                ('radius', models.IntegerField(null=True, verbose_name='Радиус зоны звукопокрытия (м)')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainApp.category', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Девайс',
                'verbose_name_plural': 'Девайсы',
            },
        ),
    ]
